### ISSUE TITLE
Git trainings

### ISSUE THREAD

**Issue by EdelMaks** [mamon151111/worktest#10]
Bogdan must pull up his git skills.

**Comment by EdelMaks** [comment]
- [x] Create new git repo
- [x] Create new project
- [x] Upload to git
- [x] Create new branch
- [x] Create new test in project
- [x] Upload to the new brach in git
- [x] Merge (pull request) the master and the new branch

**Comment by winrro** [comment]
https://github.com/winrro/SVGTest
